### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by dilbert542** [frank89722/SmileLawnComplexPack2#1]
The game crashes to desktop randomly not sure why. i have no crash report.\
遊戲崩潰到桌面的任意不知道為什麼。我沒有崩潰報告。該遊戲崩潰到桌面的任意不知道為什麼。我沒有崩潰報告。
Yóuxì bēngkuì dào zhuōmiàn de rènyì bù zhīdào wèishéme. Wǒ méiyǒu bēngkuì bàogào. Gāi yóuxì bēngkuì dào zhuōmiàn de rènyì bù zhīdào wèishéme. Wǒ méiyǒu bēngkuì bàogào.

**Comment by frank89722** [comment]
I can't help you, because I don't know why.
