### ISSUE TITLE
AE終端與硬碟櫃(有關AE方面)

### ISSUE THREAD

**Issue by asd456** [frank89722/SmileLawnComplexPack2#10]
AE合成終端.還有硬碟櫃..會莫名消失    這要怎解決....

**Comment by frank89722** [comment]
可能你要先降版本然後開輩分圖檔,然嘔在更新一次
不一定能解決,你給的資訊不夠多我只能這樣幫你

**Comment by asd456** [comment]
就是早上進去還沒事.然後吃個早餐回來.硬碟櫃莫名被泥土方塊取代..合成終端.憑空消失...還是因為我沒用你給的伺服開??應該跟這沒太大的影響吧?

**Comment by frank89722** [comment]
沒有log或是crashreoprt我通常都無法處理

**Comment by frank89722** [comment]
非原廠一概不處理

**Comment by asd456** [comment]
早已原廠

**Comment by frank89722** [comment]
沒有確切的log或是crash的crash report我沒辦法確切處理,我沒辦法'猜'到原因是什麼,目前有遇到剛剛沒是,過一陣子忽然出錯的來源通常不是模組包本身
然後,
請問你是用個版本slcp?
請問你有沒有更新過slcp?是更新後才出問題?

你有詳細閱讀回報錯誤需要準備的東西嗎?

●就是早上進去還沒事.然後吃個早餐回來.硬碟櫃莫名被泥土方塊取代..合成終端.憑空消失
sv只有你一位玩家而已嗎@_@?
會不會是其他玩家有破壞方塊或對那個方塊做了一些事情?
