### ISSUE TITLE
關於Botania(植物魔法)

### ISSUE THREAD

**Issue by asd456** [frank89722/SmileLawnComplexPack2#12]
請問香草..為何史萊姆求換仙人掌的時候..丟進去史萊姆球消失然後沒有仙人掌出來

**Comment by frank89722** [comment]
我測試正常,你是不是搞錯了?

**Comment by asd456** [comment]
昨天測試20幾個都消失還是需要使用你的伺服開服..以及使用FTB上遊戲?..理論上應該是不會影響才是

**Comment by frank89722** [comment]
如果你不是用我本來提供的發生什麼錯誤都不是我的問題,除非你是用100%從FTB上下載回來的在找我。

**Comment by asd456** [comment]
早已原廠

**Comment by frank89722** [comment]
這個問題好像有其他人也發生,我在原檔案測試正常,FTB下載後異常,我會先保留這個Issues優先處理
下個版本會修復

**Comment by frank89722** [comment]
請問你有在單人端進行過測試嗎@_@?
在單人世界李可以轉換還是不能轉換?
請問你是否有更新過sv所使用的slcp版本?
還有您當前使用的slcp是哪個版本?

**Comment by asd456** [comment]
SV2.4.0 單人2.4.0
單人端一樣不能

**Comment by frank89722** [comment]
你有更新過嗎?
從哪個版本升上來的?
你是不是忘記scripts這個資料夾的重要性忘記複製過去或是更新?

這個就是你自己的問題了,我幫不了你了,經過我多次測試單人是不可能有問題的

'這個問題好像有其他人也發生' 有問題也是scripts忘記做同步,已經救起來了
