### ISSUE TITLE
有關AE。

### ISSUE THREAD

**Issue by TNTKevins** [frank89722/SmileLawnComplexPack2#13]
香草大大您好：
【Item  7396:17】在AE裡面案 ? 會 carsh 。

隨文附上圖片：http://imgur.com/H08wvsh

**Comment by frank89722** [comment]
7396:17是哪個物品?
我看是花,每個id有可能不一樣

**Comment by asd456** [comment]
7396:17...史蒂夫礦車的wood cutting core...XXD

**Comment by frank89722** [comment]
●在AE裡面案 ? 會 carsh 。
我不太懂你在說甚麼,你是只想把它拿出來或crash?

如果是我幫不了你,這應該是模組本身的bug,我不是模組做所以沒辦法修好

**Comment by TNTKevins** [comment]
是要在AE裡面合成出來，然後會crash。

**Comment by asd456** [comment]
她按鍵按shift+?不是會直接顯示出材料(如果AE裡有材料)然後我就可以合成出來了不是嗎?..然後現在的問題點在於.在AE面板按了之後會崩潰顯示上圖的那個訊息...所以這是模組本身問題?....謝謝你幫忙解決..麻煩妳了

**Comment by frank89722** [comment]
我怎麼測試都沒辦法crash或斷線@_@
我無解O____O

去回報給ae吧XD

**Comment by asd456** [comment]
XXD..OK
