### ISSUE TITLE
有關氣壓模組

### ISSUE THREAD

**Issue by asd456** [frank89722/SmileLawnComplexPack2#16]
請問香草大大..為何氣壓模組裡面的Amadron tablet 這個東西..衝過氣壓之後使用會彈出遊戲(隨文附圖)
http://imgur.com/OirtZGO

**Comment by frank89722** [comment]
這是2.4.0 氣壓模組版本的bug
你可能要自己更新或是等模組包更新

**Comment by asd456** [comment]
0.0...大大的氣壓模組沒有改配方吧?..XD
