### ISSUE TITLE
Quest Bock - Farm like a boss

### ISSUE THREAD

**Issue by andyksch1567** [frank89722/SmileLawnComplexPack2#2]
遊玩版本 2.3.1 食物任務發生挺多的，雞、羊、牛都發生相同問題。
![2015-07-28_14 02 25](https://cloud.githubusercontent.com/assets/13533492/8924700/d4ae59e8-3532-11e5-9085-efb3a14a7c76.png)

**Comment by frank89722** [comment]
這個問題會修復,不過多久以後會修好不確定,我們的HQM任務作者最近在現實生活非常忙碌。

**Comment by andyksch1567** [comment]
謝謝，我本身也有在開實況，一定要台灣玩家整合的模組包，只是有觀眾也在問我所以我才會詢問一下而已！
2015年7月28日 下午5:57於 "frank89722" <notifications@github.com>寫道：

**Comment by frank89722** [comment]
以上bug已經修復,下個版本模組包就會修好了\@_@/

**Comment by andyksch1567** [comment]
不好意思~  我能尋求一下解決方式嘛> <  因為我自己跟幾個朋友是一起玩的，由是我這邊開多人伺服器，版本更新後
 有辦法把舊的地圖檔抓過去更新後的資料夾裡面嗎??

2015-08-03 21:19 GMT+08:00 frank89722 <notifications@github.com>:

**Comment by frank89722** [comment]
就直接把地圖黨整個複製過去就好啦0.0
