### ISSUE TITLE
無法繳交食物任務＆礦物莓果任務

### ISSUE THREAD

**Issue by QoMilkoQ** [frank89722/SmileLawnComplexPack2#4]
普通麵包拿去烤之後從烤爐拿出來沒辦法回覆任務，用別台機器烤也不行，丟地上再撿起來也不可以，不太清楚問題在哪。

羊肉的任務，一樣是烤好之後不能交任務。

雞肉的任務同上。

還有礦物莓果任務６種都有也沒辦法回任務，用漏斗丟進綁訂此任務的任務箱子裡也不可以。

不確定問題出在哪，麻煩有空幫我解答一下吧，感謝（欠身）
![default](https://cloud.githubusercontent.com/assets/13639827/9057736/a9614f06-3ace-11e5-8703-d70fc7dede78.jpg)
![default](https://cloud.githubusercontent.com/assets/13639827/9057737/a963acf6-3ace-11e5-8060-c5161df6568b.jpg)
![default](https://cloud.githubusercontent.com/assets/13639827/9057738/a9662f76-3ace-11e5-8cef-d5aa5812239f.jpg)
（目前只拍了食物部分的圖片）

**Comment by frank89722** [comment]
重複回報
