### ISSUE TITLE
任務無法繳交

### ISSUE THREAD

**Issue by QoMilkoQ** [frank89722/SmileLawnComplexPack2#6]
以太板手
![default](https://cloud.githubusercontent.com/assets/13639827/9104748/9f494e40-3c42-11e5-8ec5-e8aec89c79e5.jpg)
焚化爐
![default](https://cloud.githubusercontent.com/assets/13639827/9104752/a3d50832-3c42-11e5-9c7d-c885fe510810.jpg)
方塊破壞機
![default](https://cloud.githubusercontent.com/assets/13639827/9104757/ab9101d4-3c42-11e5-8355-efb6bb4a86a8.jpg)
自動模擬器
![default](https://cloud.githubusercontent.com/assets/13639827/9104763/b74f412a-3c42-11e5-8fff-b88f6a5932df.jpg)
礦粉
![default](https://cloud.githubusercontent.com/assets/13639827/9104775/cc66fc10-3c42-11e5-89f5-8c816bc3da8f.jpg)
食物莓果
![default](https://cloud.githubusercontent.com/assets/13639827/9104772/c6928a84-3c42-11e5-8aa3-dcdeb3089bd0.jpg)

礦物莓果(補上次的回報圖片)
![default](https://cloud.githubusercontent.com/assets/13639827/9104780/dd3e52fe-3c42-11e5-8ced-0d3973e99ec7.jpg)

今天晚上繼續努力測試 ^^

**Comment by frank89722** [comment]
下個版本會修復
