### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by m1764677** [frank89722/SmileLawnComplexPack2#7]
香草大大好
小弟開server給兩個朋友玩
日前看到SLCP2升到2.4.0
於是就重載server 把2.3.2的world資料夾複製到新的server資料夾
之後server就開不起來

crash report:
http://pastebin.com/rWSauZAu

奉上圖片
![slcp2 crash](https://cloud.githubusercontent.com/assets/13807489/9288133/2deb102e-436a-11e5-83f9-01a44b4dc28d.png)

煩請大大解惑 感謝

**Comment by frank89722** [comment]
尼好:D
這看來是thaumcraft ArcaneLamp 發光粒子被agricraft作物擋住,導致的mapcrsh,你可以試著降回2.3.2
然後先把農場上的ArcaneLamp打掉然後再做更新,應該就會修回來。

另外給你的建議,農常別放ArcaneLamp,他的發光粒子被職務取代就會mapcrash,你可以試試看factorization的燈,應該會比較好:P

**Comment by m1764677** [comment]
今天早上把ArcaneLamp打掉 然後save-all地圖
結果嘗試2.4.0的server 結果又crash了.....

crash report:
http://pastebin.com/j4v9tCXA

似乎是StorageDrawers出問題...但是看不出問題出在哪....

**Comment by frank89722** [comment]
感覺也是燈的問題
你是不是有玩sanguimancy@_@?
他的Camouflage在取得亮度的時候炸了,你要不要試試先敲掉所有ArcaneLamp@_@

**Comment by m1764677** [comment]
燈打掉之後 我有稍微玩一下 發現岩床世界有問題
另外還是不能轉2.4.0

crash report:
http://pastebin.com/5p1Myeug

岩床世界:
![bedrock](https://cloud.githubusercontent.com/assets/13807489/9293706/c41c3c28-4467-11e5-930f-77af1f13393e.png)

我朋友說 他只有挖礦而已 我今天去看 出現一大堆附魔台...OAO

**Comment by frank89722** [comment]
你是用你遠本的library下去直接封新還是用壓縮黨裡面附的@_@?
建議不要去更新library,用舊的就好。

ps:附魔台這應該算你賺到了._.(疑

**Comment by m1764677** [comment]
這個是使用原本2.3.2 library的crash report

http://pastebin.com/LM467F0M

然後這是我朋友昨天上線發現的迷之藥水(欸?

![bug](https://cloud.githubusercontent.com/assets/13807489/9297887/814d0596-44d8-11e5-8479-5ce4c472cbe6.jpg)

玩thaumcraft的不是我阿QAQ

**Comment by frank89722** [comment]
2.4.0有新增模組,應該是物品id被擠開來才會變這樣
其他部份我可能不知道要怎麼幫你@_@...
我們這邊測試目前sv都沒出現甚麼問題,這crash report也都是模組上的問題
你可以試是看把錯誤回報給出錯的模組的作者@_@

**Comment by m1764677** [comment]
好吧 感謝香草大大
看來要考慮重開地圖或回報了.....@@
