### ISSUE TITLE
植物魔法,村民

### ISSUE THREAD

**Issue by cc30115** [frank89722/SmileLawnComplexPack2#8]
香草大大好
我最近玩植物魔法時,發現不能把木頭變活木,石頭變活石
還有村民的繁殖量可再減少嗎 因為我玩的時候吋民都無限繁殖讓我超lag

**Comment by frank89722** [comment]
●我最近玩植物魔法時,發現不能把木頭變活木,石頭變活石
你確定?不是你放錯東西嗎@_@?
●村民的繁殖量可再減少嗎 因為我玩的時候吋民都無限繁殖讓我超lag
我沒辦法控制原版Minecraft的設定
