### ISSUE TITLE
MFR 與 Forestry

### ISSUE THREAD

**Issue by lovehoex6113** [frank89722/SmileLawnComplexPack2#9]
MFR的收割機採Forestry的蘋果橡樹 採收的同時就直接遊戲閃退

log在裡面https://drive.google.com/open?id=0B-oUEjtrM2rXflV2RFdWNHphOVRMclJDalBlbUJHb1JSQ09QYXVXNDJWQWZLZDF1dGZ6S1U

那請問我現在要怎麼回到之前玩的存檔??
現在還沒進入遊戲畫面就直接閃退了 T_T
版本是2.4.0

**Comment by frank89722** [comment]
這應該是MFR的問題
遇到這種錯誤你可以試著回報給MFR作者

●那請問我現在要怎麼回到之前玩的存檔??
如果你沒有更改模組包內容的話你應該會自動備分地圖檔,你可以到minecraft/backups裡面去翻
(如果你忘記是甚麼時候crash的你可以參考你第一次因為這件事所crash的crash report產生時間)

**Comment by lovehoex6113** [comment]
恩恩  感謝香草大大  >_^
